#!/usr/bin/env node
/**
 * Apply patch files to each submodule.
 *
 * Each patch in ./patches/ was generated by generate-patches.js and captures
 * the diff between origin/main and the desired working-tree state.
 *
 * Usage:
 *   node scripts/apply-patches.js            # apply all patches
 *   node scripts/apply-patches.js --check    # dry-run (verify patches apply cleanly)
 */

import { execSync } from 'child_process';
import { dirname, join, basename } from 'path';
import { fileURLToPath } from 'url';
import { existsSync, statSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '..');
const PATCHES_DIR = join(PROJECT_ROOT, 'patches');

const args = process.argv.slice(2);
const CHECK_ONLY = args.includes('--check');

const SUBMODULES = [
  { path: 'packages/pear-wrk-wdk', patch: 'pear-wrk-wdk.patch' },
  { path: 'packages/wdk-react-native-provider', patch: 'wdk-react-native-provider.patch' },
  { path: 'examples/wdk-starter-react-native', patch: 'wdk-starter-react-native.patch' },
];

function run(cmd, cwd) {
  return execSync(cmd, { cwd, encoding: 'utf-8', maxBuffer: 1024 * 1024 * 50 }).trimEnd();
}

let ok = true;

for (const { path: subPath, patch } of SUBMODULES) {
  const absPath = join(PROJECT_ROOT, subPath);
  const name = basename(subPath);
  const patchFile = join(PATCHES_DIR, patch);

  if (!existsSync(patchFile)) {
    console.warn(`  [${name}] patch file not found: ${patchFile} — skipping`);
    continue;
  }

  const bytes = statSync(patchFile).size;
  if (bytes === 0) {
    console.warn(`  [${name}] patch file is empty — skipping`);
    continue;
  }

  if (!existsSync(absPath)) {
    console.error(`  [${name}] submodule directory not found: ${absPath}`);
    console.error(`  Run: git submodule update --init --recursive`);
    ok = false;
    continue;
  }

  const checkFlag = CHECK_ONLY ? '--check' : '';
  try {
    run(`git apply ${checkFlag} --whitespace=fix "${patchFile}"`, absPath);
    const action = CHECK_ONLY ? 'verified' : 'applied';
    console.log(`  [${name}] ${action}  (${bytes} bytes)`);
  } catch (err) {
    const action = CHECK_ONLY ? 'check failed' : 'apply failed';
    console.error(`  [${name}] ${action}: ${err.message.trim()}`);
    ok = false;
  }
}

if (!ok) {
  process.exit(1);
}

console.log('\nDone.');
